spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/employee/**
          filters:
            - AuthFilter

        - id: account-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**